version: '3.8'

services:
  ecommerce-agent:
    build: .
    container_name: ecommerce-email-agent
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTO_START_AGENT=true
      - CHECK_INTERVAL=60000
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: ecommerce-network