name: mail_processor_mikro_template
description: Mikro-Agent Template für Mail-Verarbeitung
version: 1.0.0
category: mail_processing

template:
  name: complete_mail_processor
  type: mikro
  description: Verarbeitet eingehende E-Mails komplett
  pipeline_mode: sequential
  
  nano_agents:
    - name: imap_connector
      template_ref: mail_operations/imap_connect
      config:
        retry_on_failure: true
        max_retries: 3
        
    - name: email_fetcher
      template_ref: mail_operations/fetch_emails
      config:
        batch_size: 50
        process_attachments: true
        
    - name: content_parser
      template_ref: mail_operations/parse_email_content
      config:
        extract_all_entities: true
        language: de
        
    - name: email_classifier
      template_ref: mail_operations/classify_email
      config:
        use_ml_model: true
        confidence_threshold: 0.8
        
    - name: database_saver
      template_ref: mail_operations/save_email_to_db
      config:
        add_classification_tags: true
        create_audit_log: true
        
  data_flow:
    - from: imap_connector
      to: email_fetcher
      mapping:
        connection_id: connection_id
        
    - from: email_fetcher
      to: content_parser
      mapping:
        email_content: emails[*].body
        
    - from: content_parser
      to: email_classifier
      mapping:
        email_content: parsed_content.plain_text
        entities: parsed_content.entities
        
    - from: email_classifier
      to: database_saver
      mapping:
        category: category
        tags: [category, subcategory]
        
  error_handling:
    on_nano_failure:
      strategy: retry_with_backoff
      max_attempts: 3
      notify_on_final_failure: true
      
  monitoring:
    track_metrics:
      - emails_processed
      - classification_accuracy
      - processing_time
      - error_rate

---

name: attachment_handler_mikro_template
description: Mikro-Agent Template für Attachment-Verarbeitung
version: 1.0.0
category: mail_processing

template:
  name: attachment_processor
  type: mikro
  description: Verarbeitet E-Mail Anhänge
  pipeline_mode: parallel
  
  nano_agents:
    - name: attachment_downloader
      action_type: file_download
      config:
        temp_directory: /tmp/attachments
        
    - name: virus_scanner
      action_type: security_scan
      config:
        scan_engine: clamav
        quarantine_threats: true
        
    - name: ocr_processor
      action_type: ocr
      config:
        languages: [de, en]
        output_format: text
        
    - name: document_classifier
      action_type: classification
      config:
        document_types: [invoice, contract, report, other]
        
  parallel_config:
    max_concurrent: 3
    timeout_seconds: 300
    
  output_aggregation:
    strategy: merge_results
    include_all_outputs: true